### ISSUE TITLE
Handling really long lasting task?

### ISSUE THREAD

**Issue by wysow** [zf-fr/zfr-eb-worker#53]
Hello guys, I'm wondering how are you handling really long lasting task with this tool? I mean I have a process which is scraping some data during more than 10 minutes and I don't really find a good way to avoid timeouts here... Do you know a way to handle that?

**Comment by bakura10** [comment]
Hi,

As far as I remember Beanstalk allows you to configure a very long visibility timeout: http://docs.aws.amazon.com/fr_fr/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#using-features-managing-env-tiers-worker-settings

On your case, you should configure a long inactivity timeout (superior to 10 minutes) and the Beanstalk worker iwll baiscallly wait for an answer for the given time. You will also need to make a visibility timeout slightly larger than the inactivity timeout (one additional second is often enough).

The workflow will become:

1) Your job is inserted.
2) The Beanstalk daemon will pull your message from the queue.
3) It will do a HTTP POST to your server (which can be processed then by ZfrEbWorker) and will wait up to "inactivity timeout" setting.
4) If the server returns a 200 before this inactivity timeout, the daemon will delete it from the queue. Otherwise, if your server takes more time than inactivity timeout to answer, the worker will consider this as a mistake, and will do not delete it. As a consequence, after the visibility timeout, delay, the job will be retried.

I'm closing this for now as this question is more related to Beanstlak rather than this lib, but I hope it clarifies it :).

**Comment by bakura10** [comment]
PS : apparently Beanstalk allows you up to 36000 seconds of inactivity timeout, so 10 minutes indeed... so yeah you willl be limited to that unfortunately :(.

**Comment by wysow** [comment]
@bakura10 Thanks for your clear answer, will investigate this further...
